-- 코드를 입력하세요
SELECT 
    HISTORY_ID,
    ROUND(DAILY_FEE * (DATEDIFF(h.END_DATE,h.START_DATE)+1)
    * (case 
    when DATEDIFF(END_DATE,START_DATE)+1 < 7 then 1
    when DATEDIFF(END_DATE,START_DATE)+1 < 30 then 0.95
    when DATEDIFF(END_DATE,START_DATE)+1 < 90 then 0.92
    else 0.85 end)) as 'FEE'
FROM
    CAR_RENTAL_COMPANY_CAR C 
JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE
    C.CAR_TYPE = '트럭'
GROUP BY
    HISTORY_ID
ORDER BY
    FEE DESC ,HISTORY_ID DESC
